### ISSUE TITLE
Pass an custom ObjectMapper to the ApiClient

### ISSUE THREAD

**Issue by yinan-symphony** [finos/symphony-bdk-java#438]
## Feature Request
As BDK user, I'd like to be able to pass a custom ObjectMapper to the ApiClient. 

### Description of Problem:
This feature allows us to have a specific marshalling configuration for some special java objects, e.g. datetime, by default it is mapped into a long type, while we need a string in a specific format. Jira ticket https://perzoinc.atlassian.net/browse/PLAT-10517

...please resist the temptation to describe your request in terms of a solution.  Job Story form ("When [triggering condition], I want to [motivation/goal], so I can [outcome].") can help ensure you're expressing a problem statement.

### Potential Solutions:
...clearly and concisely describe what you want to happen. Add any considered drawbacks.

... if you've considered alternatives, clearly and concisely describe those too.

**Comment by symphony-thibault** [comment]
Hi @yinan-symphony, 

Could you check if this [example](https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/blob/5cec2c569632d735a458e24f41794e1c98b8d633/symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/AdvancedBdkSetupMain.java) from PR https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/pull/447 is what you were requesting? 

Thanks!

**Comment by yinan-symphony** [comment]
Hi @symphony-thibault ,

That looks great, thank you very much!
