### ISSUE TITLE
HttpClient NPE bug when add queryparam

### ISSUE THREAD

**Issue by symphony-hong** [finos/symphony-bdk-java#462]
## Bug Report
When we try to add a query param to a HttpClient instance, a NPE will be thrown because the `queryParams` in `RequestConfig` was initialised with `null` and same for `headers`, `cookies` and `formParams`.
[Ref](https://github.com/finos/symphony-bdk-java/blob/70745c703147d1ba08eeaacad18868c18c237091/symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/HttpClient.java#L373-L376)

### Steps to Reproduce:
Reproduce with the unittest:
```
final HttpClient httpClient = HttpClient.builder(this::mockedApiClientBuilder)
      .basePath("https://localhost:8080")
      .header("Connection", "Keep-Alive")
      .header("Keep-Alive", "timeout=5, max=1000")
      .cookie("foo", "bar")
      .build();

httpClient.queryParam("test", "test");
```

### Expected Result:
The query param is added successfully.
Same for `headers`, `cookies`, `formParams`

### Actual Result:
```
java.lang.NullPointerException
	at com.symphony.bdk.http.api.HttpClient$RequestConfig.appendQueryParam(HttpClient.java:394)
	at com.symphony.bdk.http.api.HttpClient.queryParam(HttpClient.java:182)
	at com.symphony.bdk.http.api.HttpClientTest.usage(HttpClientTest.java:22)
```

### Environment:
symphony-bdk-2.1.0

**Comment by symphony-thibault** [comment]
@symphony-hong PR created https://github.com/finos/symphony-bdk-java/pull/463

**Comment by symphony-thibault** [comment]
Release [2.1.1](https://github.com/finos/symphony-bdk-java/releases/tag/2.1.1) should be available soon in [Maven Central](https://oss.sonatype.org/#nexus-search;quick~org.finos.symphony.bdk).

**Comment by symphony-youri** [comment]
Do we need to merge into master too?

**Comment by symphony-thibault** [comment]
Already backported onto `main` : https://github.com/finos/symphony-bdk-java/commit/723a4a778af046ae8482066817963a9a79345550
