### ISSUE TITLE
🔫  Bulletproof DatafeedLoop

### ISSUE THREAD

**Issue by symphony-thibault** [finos/symphony-bdk-java#464]
### Context
One the most important feature of the BDK is certainly the [Datafeed Loop](https://github.com/finos/symphony-bdk-java/blob/main/docs/datafeed.md) that allows your bot application to receive [Real Time Events](https://developers.symphony.com/restapi/docs/real-time-events). The health of your bot strongly depends on this DF Loop. A broken DF Loop means that your bot cannot receive chat events and therefore cannot properly works. 

### Problem
When using the Spring Boot wrapper, the DF Loop [is executed as a separate thread](https://github.com/finos/symphony-bdk-java/blob/main/symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/service/DatafeedAsyncLauncherService.java) in order to not block the main thread. This is quite different for a pure Java application, when the DF Loop is usually started as part of the main thread and blocks this one until the loop (e.g. `while(true) { readDatafeed(); }` is still running). 

We already implemented a dedicated datafeed retry strategy that can be configured as such: 
```yaml
# config.yaml
datafeed:
  retry:
    maxAttempts: 6
    initialIntervalMillis: 2000
    multiplier: 1.5
    maxIntervalMillis: 10000
```
Reaching the `maxAttempts` value means that the loop will exit and thus its thread will stop as well. Causing an unrecoverable state for your bot application. 

❓  We would like to figure out what could be the best strategy to handle this bad situation, when your container is still alive but the DF Loop has crashed making your bot application unusable. 

### Proposed solution
One of the most straightforward solution that came to our mind is to make `maxAttemps` value almost infinite (e.g. equals to `Integer.MAX_VALUE`). Depending on the others retry parameters (`initialIntervalMillis`, `multiplier` and `maxIntervalMillis`) this would make the loop retrying for several years, so let's say forever! 

#### Config issue
Let's imagine that your BDK config contains an issue (for instance a wrong pod url). Your container successfully starts up but the DF Loop directly starts retrying forever, making your container-orchestrator unable to detect any issue.

**Comment by symphony-youri** [comment]
I would perhaps go with maxAttemps=-1 as the default for the DF loop in order to express infinite retries
