### ISSUE TITLE
Wrong pagination logic for listAllUserFollowing and listAllUserFollowers

### ISSUE THREAD

**Issue by symphony-elias** [finos/symphony-bdk-java#468]
## Bug Report
Today we are using an [offset based pagination](https://github.com/finos/symphony-bdk-java/blob/main/symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/PaginatedService.java#L72) logic for endpoints that have a cursor based pagination:
* [UserService.listAllUserFollowers](https://github.com/finos/symphony-bdk-java/blob/main/symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java#L596)
* [UserService.listAllUserFollowing](https://github.com/finos/symphony-bdk-java/blob/main/symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java#L652)

However, the documentation of these endpoints [list user followers](https://developers.symphony.com/restapi/reference#list-user-followers) and [list user followed](https://developers.symphony.com/restapi/reference#list-users-followed) explains the logic for pagination:
* the `after` query param means we fetch the item of rank `after + 1`
* if `pagination.cursors.after` is not present in the response payload, it means last item is in the current payload

Logic should go as follows:
* first call with no `after` and no `before` query param
* next calls are done with `after` query param retrieved from the previous response payload
* when `after` is not present in the response payload, we are done

**Comment by symphony-mariacristina** [comment]
On this two endpoints we are currently using a [CursorPaginationAttribute](https://github.com/finos/symphony-bdk-java/blob/6d9ccba71f7f35da4ee0a45d210ab2e19bb74586/symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/model/CursorPaginationAttribute.java#L13) in which we set:
- `Before` parameter: 0
- `After` parameter: offset, which starts from 0
See code [here](https://github.com/finos/symphony-bdk-java/blob/main/symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java#L597).
So let's say we make the following call:
`Stream<Long> listAllUsers = bdk.users().listAllUserFollowers(13056700580913L, new StreamPaginationAttribute(2, 100));`
in which 2 represents the size of elements to retrieve in one call (`limit`).
This will make different calls with the following parameters:
- offset(after) = 0, chunkSize(limit) = 2
- offset = 2, chunkSize = 2
- offset = 4, chunkSize = 2
- ... till the end of the list, where after is null.
This behaviour is actually the expected one. What we could say in fact is that in case we want to return the list of all followers  the process is the same as for the offset one. What makes the two paginations differ is in the fact that the cursor one it has the concept of before/after page which the other one does not have, but in terms of parsing the whole list they behave exactly in the same way.
