### ISSUE TITLE
Update User-Agent default value to comply with RFC 7231 section 5.5.3

### ISSUE THREAD

**Issue by symphony-elias** [finos/symphony-bdk-java#471]
Default user-agent is currently `"Symphony BDK/" + getBdkVersion() + "/java/" + System.getProperty("java.version")` as defined here: https://github.com/finos/symphony-bdk-java/blob/main/symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/util/ApiUtils.java#L14

According to https://tools.ietf.org/html/rfc7231#section-5.5.3 we should have no spaces within the same 
product item in the User-Agent field.

### Expected Result:
I would propose to have the following instead: 
`"Symphony-BDK-Java/" + getBdkVersion() + " Java/" + System.getProperty("java.version")`

**Comment by symphony-youri** [comment]
Is it ok to have a space here _getBdkVersion() + " Java/"_?

**Comment by symphony-elias** [comment]
> Is it ok to have a space here _getBdkVersion() + " Java/"_?

I would say so, check the example here: https://tools.ietf.org/html/rfc7231#section-5.5.3
