### ISSUE TITLE
Module system 

### ISSUE THREAD

**Issue by symphony-thibault** [finos/symphony-bdk-java#479]
> **DRAFT, IN PROGRESS**

The purpose of this issue is to introduce and specify a new module system for the BDK library. We want to empower contributors to create their own modules or plugins in separate repositories, without necessary having to make their contributions directly in the BDK codebase. 

## Overview

```java
public class MyModule implements BdkModule, BdkLifecycleAware, BdkConfigurationAware {
  
  @Override // provided by BdkConfigurationAware
  public void onConfigurationSet(BdkConfig config) {}

  @Override // provided by BdkLifecycleAware
  public void onCoreInitialized(SymphonyBdk bdk) {}
}
```

## Loading system
To explore: 
- manual loading through [`SymphonyBdkBuilder`](https://javadoc.io/doc/org.finos.symphony.bdk/symphony-bdk-core/latest/com/symphony/bdk/core/SymphonyBdkBuilder.html): 
```java
SymphonyBdk bdk = new SymphonyBdkBuilder().config(config).withModule(MyModule.class).build();
```
- using JDK [`ServiceLoader`](https://docs.oracle.com/javase/9/docs/api/java/util/ServiceLoader.html)

## Module Service
On the other hand, a developer should also be able to retrieve a module service, for instance using: 

```java
MyModuleService moduleService = bdk.lookupModuleService(MyModuleService.class); 
```

**Comment by symphony-youri** [comment]
Supporting an Agentless architecture in the BDK is one of the use case for extension.

While the service loader approach has the benefit of being natively supported it is also less explicit and a bit of magic happening at runtime.
The module approach with clear and well defined extension points might help to make it more explicit. We could take inspiration from Jackson modules for instance.

For instance, here is an extension point that was defined:

```java
public interface BdkModule {

  <T> T getService(AuthSession authSession, ApiClientFactory apiClientFactory, RetryWithRecoveryBuilder<?> retryBuilder,
      Class<T> messageServiceClass);

}
```

What we want to make sure is to encapsulate the method's parameters in an object to easily evolve those without breaking compatibility (at least we would be free to pass new data around).
