### ISSUE TITLE
Allow configuration to disable datafeed persistence for v1

### ISSUE THREAD

**Issue by anthony-symphony** [finos/symphony-bdk-java#481]
## Feature Request
Allow configuration to disable datafeed persistence for v1

### Description of Problem:
Some sites don't handle the reuse of datafeed properly and it can cause the bot to be non-functional.

**Comment by symphony-youri** [comment]
Counter argument for it (my personal point of view):
As it is for a very specific use case and not the behavior we want to promote I would prefer not to pollute the code base and configuration's format with a specific toggle. IMHO this can be worked around by deleting the datafeed id file prior to starting the bot.
Also we would prefer users to move to DFv2.

**Comment by anthony-symphony** [comment]
@symphony-youri  @symphony-thibault 

My personal view is if we are doing things on behalf of the developer it should be configurable as what may work for one may not work for them. I am all for configurability and customization but, understand that from a maintenance standpoint it can get quite hectic. Let me check with the stakeholder that raised this issue.

**Comment by anthony-symphony** [comment]
Feedback from the customer:

We would prefer to resolve this issue without needing custom code. Is the team still considering adding the config to turn off reusing the old datafeed ID? If not, at the very least the error should be handled gracefully and a new datafeed should be created and read from. Currently, if reading from the old datafeed it returns a 498 and the bot shuts down. Proper error handling should be that a new datafeed is created instead.

**Comment by symphony-youri** [comment]
That's odd, 498 is not an official http status (498 Invalid Token (Esri) Returned by ArcGIS for Server. Code 498 indicates an expired or otherwise invalid token.).
The way it was done is that indeed if the DF cannot be used it should be recreated. When this happens, do they get an error message along with the 498?

**Comment by anthony-symphony** [comment]
Does it retry and create a new datafeed as long as its not 204 or 200 or only when it gets a 400 (Datafeed does not exist)? It might be the case where they have something in front of the agent which returned a 489 and instead of recreating the datafeed since its not a 400 it just keeps retrying the read.

**Comment by symphony-thibault** [comment]
> Currently, if reading from the old datafeed it returns a 498 and the bot shuts down

This is definitely not a normal behaviour as Agent should never return `498` http status. Currently, the [DatafeedLoopV1 recreates new datafeed on `400` errors](https://github.com/finos/symphony-bdk-java/blob/main/symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1.java#L118), as defined by our API contract.

> We would prefer to resolve this issue without needing custom code.

I completely understand customer POV, but we need here to keep in mind that DFv1 is now deprecated, and we therefore don't want to bring those kind of custom requirements in the BDK2.0 codebase. 

I still believe that [this example](https://github.com/finos/symphony-bdk-java/issues/481#issuecomment-811151162) is quite simple to implement, versus modifying BDK2.0 codebase.

**Comment by ystan-** [comment]
Closing this issue since DFv1 is scheduled for deprecation and DFv2 mechanics are different
