### ISSUE TITLE
Initialise DistributedTracingContext in AbstractActivity

### ISSUE THREAD

**Issue by yinan-symphony** [finos/symphony-bdk-java#482]
## Feature Request
DistributedTracingContext is initialised for the rest api request today, i would like to have the same traceability for the activities. 

### Description of Problem:
When BOT receives a message from DF, i'd like to the traceability as we do in the rest api.

### Potential Solutions:
Initialise the DistributedTracingContext at the start point of the #processEvent.

... if you've considered alternatives, clearly and concisely describe those too.

**Comment by yinan-symphony** [comment]
@symphony-youri 
yes, we should do it for all events, not only activities.
well, a random value would be fine IMO, just as what we have for rest requests.

**Comment by symphony-youri** [comment]
Note for implementation: also check on the Agent side that if we have a trace id (or generate one) that we can correlate what happens on the agent side / bot side.

**Comment by symphony-thibault** [comment]
+ trace (`debug` mode) DF events when dispatched to listeners. Also we might consider handling exceptions raised by the listener.

**Comment by symphony-thibault** [comment]
Hi @yinan-symphony, 

Pull request now opened https://github.com/finos/symphony-bdk-java/pull/489
