### ISSUE TITLE
Some links in the GH pages documentation are dead

### ISSUE THREAD

**Issue by symphony-elias** [finos/symphony-bdk-java#510]
## Bug Report

In https://symphony-bdk-java.finos.org/datafeed.html (or https://github.com/finos/symphony-bdk-java/blob/main/docs/activity-api.md) most of the external links are invalid following the revamp of the Symphony developers documentation. Links all redirect to the home page of the Symphony developers documentation.
https://symphony-bdk-java.finos.org/symphony-bdk-examples/bdk-multi-instances-example leads to 404 error.

## Expected result
External links in the documentation should be up to date

**Comment by RanabirChakraborty** [comment]
Hello @symphony-elias can I take a look into it?

**Comment by symphony-elias** [comment]
> Hello @symphony-elias can I take a look into it?

Hello @RanabirChakraborty of course! Feel free to open a PR referencing this issue
