### ISSUE TITLE
Custom style

### ISSUE THREAD

**Issue by JosephP91** [finos/symphony-bdk-java#520]
Hi! I was wondering if it's possibile to add custom CSS styles to messageML tags. In my specific case, I need to color a portion of the text with a different color than the other portion, but I cannot use certain css options. Is it possible?

**Comment by symphony-youness** [comment]
Hi @JosephP91 , maybe you can use inline styles.

We have a renderer tool that you can use: https://renderer-tool.app.symphony.com/
On the right side, you have a dropdown where you can select `Text Formatting` and it will show you an example of inline styling a span tag.

**Comment by JosephP91** [comment]
Hi @symphony-youness ,

yes, I was using the renderer tool to make some test, but as far as I can see, not all the CSS properties are supported. Specifically, I was trying to use `-webkit-background-clip: text;`, but the tool says it's an unsupported tag.

Is there a way to use it?

**Comment by symphony-adnane** [comment]
Unfortunately @JosephP91 not all CSS props are allowed, 
If you need to color just a portion of text, did you think about splitting that section in a span and applying the style you want? (using style="color: ...")

**Comment by JosephP91** [comment]
Yes I though about it, but I was trying to follow the easy way with a simple CSS prop. But at this point I think I'll go for that. Thank you!
