### ISSUE TITLE
pause and resume on extended api

### ISSUE THREAD

**Issue by JosephP91** [finos/symphony-bdk-java#536]
Hi all! I was trying to use the pause() and resume() methods of the extended api, using the render method (https://docs.developers.symphony.com/building-extension-applications-on-symphony/overview-of-extension-api/extension-api-services/entity-service#pause-and-resume). 

I was trying to find an example of the usage, but I couldn't find nothing. Can you give me one? Specifically, I need to see how to pass the iFrameId to the pause method.

**Comment by symphony-thibault** [comment]
Hi @JosephP91, 

Unfortunately we won't be able to help you here as this repo as your issue seems to be related to the extension app API. 

Please contact support@symphony.com instead. 

Thanks for your understanding!
