### ISSUE TITLE
Add Message ID and Stream ID to FormReplyActivity's FormReplyContext

### ISSUE THREAD

**Issue by ystan-** [finos/symphony-bdk-java#621]
### Description of Problem:
Using FormReplyActivity to capture Elements form submissions currently does not provide the Message ID from the originating form. This blocks workflows attempting to either suppress or update the message containing the form that was just submitted.

For message update, message id alone is not sufficient and stream id is also required. Obtaining stream id currently requires a call 3 levels deep: `context.getSourceEvent().getStream().getStreamId()`.

### Potential Solutions:
Add `getMessageId()` and `getStreamId()` to FormReplyContext. This will allow the most commonly-used identifiers - Form ID, Message ID and Stream ID - to be accessed easily when processing form submissions.

**Comment by symphony-youri** [comment]
Good idea, seems like a small and easy improvement!

**Comment by symphony-thibault** [comment]
PR created @ystan- https://github.com/finos/symphony-bdk-java/pull/622 :)
