### ISSUE TITLE
Migrate to FINOS Security Scanning

### ISSUE THREAD

**Issue by ystxn** [finos/symphony-bdk-java#691]
### Description of Problem:
FINOS has rolled out a new security scanning GitHub action that effectively replaces the capabilities that whitesource/mend provides as part of the CI pipeline. The new scan performs dependency vulnerability scanning and offers an offline cli so developers can pre-scan the code base to preview the scan results before pushing a PR. It also has an optional component that facilitates static code analysis.

### Potential Solutions:
Replace all instances of whitesource in action pipelines with the following action instead:
https://github.com/finos/security-scanning

**Comment by yinan-symphony** [comment]
Done in release symphony-bdk-2.11.1
