### ISSUE TITLE
Make symphony-springboot-starter compatible with spring-boot 3

### ISSUE THREAD

**Issue by mikekay68** [finos/symphony-bdk-java#758]
### Description of Problem:
I tried to update spring-boot to version 3 and app stopped working. So far the problem is with javax.ws.rs-api. It's no longer available via spring. This is what available - jakarta.ws.rs-api. But probably there is more.  I am using latest bdk version 2.13.0. it brings  javax.ws.rs-api via org.finos.symphony.bdk:symphony-bdk-http-jersey2:jar:2.13.0 but makes it incompatible with spring-boot 3.

### Potential Solutions:
update spring-boot dependency to version 3. Spring is using jakarta.* instead of javax.*

... if you've considered alternatives, clearly and concisely describe those too.

**Comment by symphony-soufiane** [comment]
Hi @mikekay68, thank you for raising this issue.

We are currently thinking about spring-boot 3 migration. Please note that spring-boot 3 requires JDK 17 so this migration would impact the java-bdk-core module as well which will be a breaking change. One plan we are exploring is to maintain 2 BDK branches, one with spring-boot 3 and JDK 17 in addition to the current main branch. Thus, customers will need to use JDK 17 or stick with spring-boot 2 based BDK. 

We will let you know when there is any update regarding this.

**Comment by yinan-symphony** [comment]
BDK 3.0 was released, https://github.com/finos/symphony-bdk-java/releases/tag/v3.0.0.

its using SpringBoot 3.2.2 and JDK17.
